### ISSUE TITLE
Installation of "avs.ui.apps-1.0.1" giving error when uploading the image

### ISSUE THREAD

**Issue by ashish431** [valtech/aem-virus-scan#6]
15.04.2021 21:44:11.613 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=de.valtech.avs.core.service.scanner.ClamScannerEngine)] de.valtech.avs.core Service [de.valtech.avs.core.service.scanner.ClamScannerEngine,10896, [de.valtech.avs.api.service.scanner.AvsScannerEnine]] ServiceEvent REGISTERED
15.04.2021 21:44:21.441 *ERROR* [HealthCheck AVS Self Check] de.valtech.avs.core.service.scanner.ClamScannerEngine Error during scanning
java.io.IOException: Cannot run program "/usr/local/bin/clamdscan": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at de.valtech.avs.core.service.scanner.ClamScannerEngine.scan(ClamScannerEngine.java:72) [de.valtech.avs.core:1.0.1]
	at de.valtech.avs.core.service.AvsServiceImpl.scan(AvsServiceImpl.java:93) [de.valtech.avs.core:1.0.1]
	at de.valtech.avs.core.service.AvsServiceImpl.scan(AvsServiceImpl.java:78) [de.valtech.avs.core:1.0.1]
	at de.valtech.avs.core.healthcheck.SelfCheckHealthCheck.checkSampleScan(SelfCheckHealthCheck.java:102) [de.valtech.avs.core:1.0.1]
	at de.valtech.avs.core.healthcheck.SelfCheckHealthCheck.checkActiveScannersAvailable(SelfCheckHealthCheck.java:90) [de.valtech.avs.core:1.0.1]
	at de.valtech.avs.core.healthcheck.SelfCheckHealthCheck.execute(SelfCheckHealthCheck.java:59) [de.valtech.avs.core:1.0.1]
	at org.apache.sling.hc.core.impl.executor.HealthCheckFuture$1.call(HealthCheckFuture.java:66) [org.apache.sling.hc.core:1.2.10]
	at org.apache.sling.hc.core.impl.executor.HealthCheckFuture$1.call(HealthCheckFuture.java:51) [org.apache.sling.hc.core:1.2.10]
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.apache.sling.hc.core.impl.executor.HealthCheckExecutorImpl$3.run(HealthCheckExecutorImpl.java:378) [org.apache.sling.hc.core:1.2.10]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 17 common frames omitted

**Comment by brandongoldman** [comment]
@Valtechadmin Can you please advise? Facing same problem.

**Comment by brandongoldman** [comment]
@ashish431 did you find a resolution?

**Comment by gruberrolandvaltech** [comment]
Please configure the proper path to your local Clam application. In this example it tries to run /usr/local/bin/clamdscan.
See https://github.com/valtech/aem-virus-scan - Clam Scanning Engine
